# SPDX-FileCopyrightText: Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR MIT

# NOTE Documentation: https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html





variables:
  # Accept default answer for all questions during Debian/Ubuntu
  # package management:
  DEBIAN_FRONTEND: "noninteractive"





codecheck: &codecheck
  stage: build
  image: ubuntu:22.04
  tags:
    - Linux
  interruptible: true
  script:
    - exit # Dummy value
  rules:
    - when: always
      allow_failure: false
  artifacts:
    expire_in: 20 weeks
    when: always
    paths:
      - artifact_*





codecheck_automatic_integration:
  <<: *codecheck
  before_script:
    - apt-get update --assume-yes
    - apt-get install --assume-yes --no-install-recommends cmake make clang clang-format liblcms2-dev liblcms2-2 pkgconf extra-cmake-modules qt6-base-dev qt6-base-dev-tools qt6-l10n-tools libegl-dev qt6-tools-dev qt6-tools-dev-tools git
  script:
    - ./.codecheck-automatic-integration.sh





codecheck_cmakelint:
  <<: *codecheck
  before_script:
    - apt-get update --assume-yes
    - apt-get install --assume-yes --no-install-recommends python3-pip
    - echo "pip version:" && pip --version
    - pip install cmakelint
    - echo "cmakelint version:" && cmakelint --version
  script:
    - ./.codecheck-cmakelint.sh





codecheck_cppcheck:
  # Like the cppcheck that invent.kde.org provides, but exit status depends
  # on if issues have been found or not. And it runs always, and not only
  # when C++ code has changed.
  stage: build
  image: kdeorg/ci-suse-qt515:latest
  tags:
    - Linux
  interruptible: true
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities
  script:
    - python3 -u ci-utilities/run-cppcheck.py --project $CI_PROJECT_NAME --branch $CI_COMMIT_REF_NAME
    - if [ "$(cat cppcheck.json)" == "[]" ]; then
    -     echo "cppcheck did not find any issues."
    -     exit 0
    - else
    -     echo "cppcheck found issues."
    -     exit 1
    - fi
  rules:
    - when: always
      allow_failure: false
  artifacts:
    expire_in: 20 weeks
    when: always
    paths:
      - cppcheck.json
    reports:
      codequality: cppcheck.json





codecheck_doxygen:
  <<: *codecheck
  before_script:
    - apt-get update --assume-yes
    - apt-get install --assume-yes --no-install-recommends doxygen graphviz cmake make clang liblcms2-dev liblcms2-2 pkgconf extra-cmake-modules qt6-base-dev qt6-base-dev-tools qt6-l10n-tools libegl-dev qt6-tools-dev qt6-tools-dev-tools wget
    - echo "doxygen version:" && doxygen --version
    - echo "graphviz dot version:" && dot -V
    # The following commands make a graphical shell available
    # (necessary for generatescreenshots).
    - apt-get install --assume-yes --no-install-recommends xvfb openbox fonts-noto-core
    - export DISPLAY=':90'
    - Xvfb :90 -ac -screen 0 1600x1200x24+32 &
    - sleep 5s
    - openbox &
  script:
    - ./.codecheck-doxygen.sh





codecheck_qt5:
  <<: *codecheck
  before_script:
    - apt-get update --assume-yes
    - apt-get install --assume-yes --no-install-recommends cmake make clang iwyu clazy clang-tidy liblcms2-dev liblcms2-2 pkgconf extra-cmake-modules qtbase5-dev qtbase5-dev-tools qttools5-dev
  script:
    - ./.codecheck-qt5.sh





codecheck_qt6:
  <<: *codecheck
  before_script:
    - apt-get update --assume-yes
    - apt-get install --assume-yes --no-install-recommends cmake make clang iwyu clazy clang-tidy liblcms2-dev liblcms2-2 pkgconf extra-cmake-modules qt6-base-dev qt6-base-dev-tools qt6-l10n-tools libegl-dev qt6-tools-dev qt6-tools-dev-tools
  script:
    - ./.codecheck-qt6.sh





codecheck_static:
  <<: *codecheck
  script:
    - ./.codecheck-static.sh





include:
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm32.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-appimage.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-mingw64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-static.yml
  # NOTE The following line adds Linux build. Furthermore, it adds a job for
  # cppcheck, but only if there were actual changes to CPP code since last time.
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  # NOTE The following line runs reuse-lint on everything except translations.
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-static.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows.yml
