# SPDX-FileCopyrightText: 2020-2023 Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: MIT

# NOTE Documentation: https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html

variables:
  DEBIAN_FRONTEND: "noninteractive"
codecheck_custom:
  stage: build
  image: debian:testing
  interruptible: true
  before_script:
    - apt-get update
    # TODO xxx Can the following list be reduced, for example remove either
    # Qt5 or Qt6 and stick with only one of them?
    - apt-get install --yes --no-install-recommends pip doxygen graphviz cmake make cppcheck iwyu clazy pkgconf qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools clang clazy iwyu liblcms2-dev liblcms2-2 clang-tidy clang-format cmake git qt6-base-dev qt6-base-dev-tools qt6-declarative-dev qt6-declarative-dev-tools qt6-l10n-tools qt6-qmltooling-plugins qt6-tools-dev qt6-tools-dev-tools qt6-translations-l10n qt6-wayland qt6-wayland-dev qt6-wayland-dev-tools qt6-xdgdesktopportal-platformtheme qml-qt6 linguist-qt6 extra-cmake-modules xvfb openbox fonts-noto-core
    - echo "pip version:" && pip --version
    - echo "doxygen version:" && doxygen --version
    - echo "graphviz dot version:" && dot -V
    - pip install cmakelint
    - echo "cmakelint version:" && cmakelint --version
    # The following commands only make sense when a graphical shell is needed
    # (like for generatescreenshots)…
    #- export DISPLAY=':90'
    #- Xvfb :90 -ac -screen 0 1600x1200x24+32 &
    #- sleep 5s
    #- openbox &
  script:
    - ./.gitlab-ci.sh
  rules:
    - when: always
      allow_failure: true
  artifacts:
    expire_in: 20 weeks
    when: always
    paths:
      - artifact_*

codecheck_cppcheck:
  stage: build
  image: kdeorg/ci-suse-qt515:latest
  tags:
    - Linux
  interruptible: true
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities
  script:
    - python3 -u ci-utilities/run-cppcheck.py --project $CI_PROJECT_NAME --branch $CI_COMMIT_REF_NAME
  artifacts:
    expire_in: 20 weeks
    when: on_success
    paths:
      - cppcheck.json
    reports:
      codequality: cppcheck.json

reuse_everything:
  # The default reuse-lint.yml template currently excludes translation files
  # from checking. This target however checks really everything.
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  stage: build
  tags:
    - Linux
  interruptible: true
  script:
    - reuse lint

include:
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm32.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-appimage.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-mingw64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-static.yml
  # The following line adds Linux build. Furthermore, it adds a job for cppcheck,
  # but only if there were actual changes to CPP code since last time.
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-static.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows.yml
