# SPDX-FileCopyrightText: 2020-2023 Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: MIT

# NOTE Documentation: https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html

sast:
  stage: test

variables:
  DEBIAN_FRONTEND: "noninteractive"

custom_ci:
  stage: build
  image: debian:testing
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends pip doxygen graphviz
    - echo "pip version:" && pip --version
    - echo "doxygen version:" && doxygen --version
    - echo "graphviz dot version:" && dot -V
    - pip install cmakelint
    - echo "cmakelint version:" && cmakelint --version
  script:
    - ./.gitlab-ci.sh
  rules:
    - when: always
      allow_failure: true

include:
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm32.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-appimage.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-base.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-mingw64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-x86-64.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-static.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-qt6.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows-static.yml
  #- https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows.yml
# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
  - template: Security/SAST.gitlab-ci.yml
