# SPDX-FileCopyrightText: 2020-2023 Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: MIT

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'

#- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']

Options:
  #in-source-build: False
  use-ccache: False
  cmake-options: '-DADDITIONAL_WARNINGS=TRUE'
  #test-before-installing: False
  run-tests: True
  #tests-load-sensitive: False
  #per-test-timeout: 60
  setup-x-environment: True
  setup-dbus-session: True
  #force-inject-asan: False
  #ctest-arguments: ''
  require-passing-tests-on: ['@all']
  run-cppcheck: True
  cppcheck-arguments: '--enable=all --suppress=unusedFunction --inline-suppr --language=c++ --std=c++17'
  cppcheck-ignore-files: []
  #run-gcovr: True # TODO xxx Make this actually work!
  #gcovr-arguments: ''
