# SPDX-FileCopyrightText: Lukas Sommer <sommerluk@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR MIT





# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-macos:
    macos:
      # Use macOS executor for Mac build with the medium resource class
      xcode: 14.3.1
    environment:
      # From CircleCI documentation: “Homebrew, by default, will check for
      # updates at the start of any operation. […] If build speed […] are
      # a concern, this automatic update feature can be disabled. On
      # average, this can save up to two to five minutes per job.”
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      # Steps for Mac build
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Dependencies for Mac build
            brew update
            brew install cmake make qt6 wget extra-cmake-modules
      - run:
          name: Build project
          command: |
            PARALLEL_PROCESSES=$(sysctl -n hw.ncpu)
            echo Number of available CPU threads: $PARALLEL_PROCESSES
            rm -rf build
            mkdir -p build
            cd build
            cmake -DBUILD_WITH_QT6=ON ..
            cmake --build . --parallel $PARALLEL_PROCESSES
            cmake --build . --target install --parallel $PARALLEL_PROCESSES
            ctest --output-on-failure --progress
            cd ..
            rm -rf buildexamples
            mkdir -p buildexamples
            cd buildexamples
            cmake -DBUILD_WITH_QT6=ON ../examples
            cmake --build . --parallel
            cd ..
            mkdir -p screenshots
            cd screenshots
            ../build/utils/generatescreenshots --native
            zip -r ../screenshots.zip .
            cd ..
      - store_artifacts:
          path: screenshots.zip

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build-macos
